[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-Wl,--build-id=none",
  "-C","link-arg=-s"
]

[target.aarch64-linux-android]
rustflags = [
  "-C", "link-arg=-Wl,--build-id=none",
  "-C","link-arg=-s"
]

[target.armv7-linux-androideabi]
rustflags = [
  "-C", "link-arg=-Wl,--build-id=none",
  "-C","link-arg=-s"
]


